### ISSUE TITLE
fix problem

### ISSUE THREAD

**Issue by Silverfox28** [jgenco/jgenco-overlay#11]
`❯ sudo emerge --info '=sci-mathematics/rstudio-2023.03.0.386::jgenco'
Password: 
Portage 3.0.44 (python 3.10.10-final-0, default/linux/amd64/17.1/desktop/gnome/systemd, gcc-11, glibc-2.36-r7, 6.1.19-gentoo-x86_64 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-6.1.19-gentoo-x86_64-x86_64-AMD_Ryzen_7_3700X_8-Core_Processor-with-glibc2.36
KiB Mem:    32785084 total,  28693164 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Sun, 26 Mar 2023 14:00:01 +0000
Head commit of repository gentoo: 9da1c2adbbef9c70f9a25603dd853fde43677cb1
Head commit of repository jgenco: 6769a14e23a246f89332a1cbe211a5f77b9270a5

sh bash 5.1_p16-r2
ld GNU ld (Gentoo 2.39 p5) 2.39.0
app-misc/pax-utils:        1.3.5::gentoo
app-shells/bash:           5.1_p16-r2::gentoo
dev-java/java-config:      2.3.1::gentoo
dev-lang/perl:             5.36.0-r2::gentoo
dev-lang/python:           3.10.10_p3::gentoo, 3.11.2_p2::gentoo
dev-lang/rust:             1.66.1::gentoo
dev-lang/rust-bin:         1.66.1::gentoo
dev-util/cmake:            3.25.2::gentoo
dev-util/meson:            1.0.1::gentoo
sys-apps/baselayout:       2.13-r1::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-apps/systemd:          252.7::gentoo
sys-devel/autoconf:        2.13-r7::gentoo, 2.71-r5::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.39-r4::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           15.0.7-r1::gentoo
sys-devel/gcc:             11.3.1_p20221209::gentoo, 12.2.1_p20230121-r1::gentoo
sys-devel/gcc-config:      2.8::gentoo
sys-devel/libtool:         2.4.7-r1::gentoo
sys-devel/llvm:            15.0.7::gentoo
sys-devel/make:            4.3::gentoo
sys-kernel/linux-headers:  6.1::gentoo (virtual/os-headers)
sys-libs/glibc:            2.36-r7::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    volatile: True
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 24

jgenco
    location: /var/db/repos/jgenco
    sync-type: git
    sync-uri: https://github.com/jgenco/jgenco-overlay.git
    masters: gentoo
    volatile: True

brother-overlay
    location: /var/lib/layman/brother-overlay
    masters: gentoo
    priority: 50
    volatile: True

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=znver2 -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=znver2 -O2 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-march=znver2 -O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=znver2 -O2 -pipe"
GENTOO_MIRRORS="https://gentoo.mirror.garr.it/ https://mirrors.soeasyto.com/distfiles.gentoo.org/ https://ftp.uni-hannover.de/gentoo/"
LANG="it_IT.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LEX="flex"
MAKEOPTS="-j15"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/zsh"
USE="X a52 aac acl acpi alsa amd64 bluetooth branding bzip2 cairo cdda cdr cli colord crypt cups daemon dbus dri dts dvd dvdr eds encode evo exif ffmpg flac fortran gdbm gif gnome gnome-keyring gnome-online-accounts gpm gstreamer gtk gui iconv icu initramfs introspection ipv6 jack jpeg lcms libglvnd libnotify libsecret libtirpc mad matroska mng mp3 mp4 mpeg multilib nautilus ncurses networkmanager nls nptl ogg opencl opengl openmp pam pango pcre pdf png policykit polkit ppds pulseaudio readline sdl seccomp sound spell split-usr ssl startup-notification svg sysprof systemd test-rust tiff tracker truetype udev udisk udisks unicode upower usb vorbis wayland wxwidgets x264 xattr xcb xft xml xv xvid zeroconf zlib" ABI_X86="64" ADA_TARGET="gnat_2021" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2 aes avx avx2 f16c fma3 pclmul popcnt rdrand sha sse3 sse4_1 sse4_2 sse4a ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput" KERNEL="linux" L10N="it" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_10" PYTHON_TARGETS="python3_10" RUBY_TARGETS="ruby30" USERLAND="GNU" VIDEO_CARDS="amdgpu radeonsi" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS
`
`!!! When you file a bug report, please include the following information:
GENTOO_VM=openjdk-bin-11  CLASSPATH="" JAVA_HOME="/opt/openjdk-bin-11.0.18_p10"
JAVACFLAGS="-source 11 -target 11" COMPILER=""
and of course, the output of emerge --info =rstudio-2023.03.0.386
 * The complete build log is located at '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/temp/environment'.
 * Working directory: '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/work'
 * S: '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/work/rstudio-2023.03.0-386'

>>> Failed to emerge sci-mathematics/rstudio-2023.03.0.386, Log file:
`

**Comment by jgenco** [comment]
Can you [attach](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) the build log at `/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/temp/build.log`

**Comment by Silverfox28** [comment]
`[32m * [39;49;00mPackage:    sci-mathematics/rstudio-2023.03.0.386:0
[32m * [39;49;00mRepository: jgenco
[32m * [39;49;00mUpstream:   https://github.com/rstudio/rstudio/issues
[32m * [39;49;00mUSE:        abi_x86_64 amd64 electron elibc_glibc kernel_linux userland_GNU
[32m * [39;49;00mFEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 [32m*[0m Using: openjdk-bin-11
>>> Unpacking source...
>>> Unpacking rstudio-2023.03.0.386.tar.gz to /var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/work
 [32m*[0m Building NPM cache...
 [32m*[0m Checking lockfile: 
 [32m*[0m Checking npm lock file(s)
/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/temp/environment: line 4579: xxd: command not found
/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/temp/environment: line 4581: xxd: command not found
package:bindings@1.5.0       "integrity": "sha1-",
package:bindings@1.5.0       "integrity": "sha512-",
 [31;01m*[0m ERROR: sci-mathematics/rstudio-2023.03.0.386::jgenco failed (unpack phase):
 [31;01m*[0m   Package bindings@1.5.0 hash failed to match package-lock files(s)
 [31;01m*[0m 
 [31;01m*[0m Call stack:
 [31;01m*[0m     ebuild.sh, line  136:  Called src_unpack
 [31;01m*[0m   environment, line 5103:  Called npm_build_cache 'bindings@1.5.0' 'file-uri-to-path@1.0.0' 'nan@2.17.0' 'node-addon-api@5.0.0' 'node-system-fonts@1.0.1' 'unix-dgram@2.0.6'
 [31;01m*[0m   environment, line 4582:  Called npm_check_pkg_hash 'bindings@1.5.0'
 [31;01m*[0m   environment, line 4658:  Called die
 [31;01m*[0m The specific snippet of code:
 [31;01m*[0m       die "Package $1 hash failed to match package-lock files(s)"
 [31;01m*[0m 
 [31;01m*[0m If you need support, post the output of `emerge --info '=sci-mathematics/rstudio-2023.03.0.386::jgenco'`,
 [31;01m*[0m the complete build log and the output of `emerge -pqv '=sci-mathematics/rstudio-2023.03.0.386::jgenco'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=openjdk-bin-11  CLASSPATH="" JAVA_HOME="/opt/openjdk-bin-11.0.18_p10"
JAVACFLAGS="-source 11 -target 11" COMPILER=""
and of course, the output of emerge --info =rstudio-2023.03.0.386
 [31;01m*[0m The complete build log is located at '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/temp/build.log'.
 [31;01m*[0m The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/temp/environment'.
 [31;01m*[0m Working directory: '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/work'
 [31;01m*[0m S: '/var/tmp/portage/sci-mathematics/rstudio-2023.03.0.386/work/rstudio-2023.03.0-386'`

**Comment by Silverfox28** [comment]
I solved it by installing the xxd package from the nymphos overlay. Thank you very much.

**Comment by jgenco** [comment]
I'm sorry for that, as you see  it needed `xxd`. On my system it is provided by `app-editors/vim-core` which I'm NOT going to depend on.  I'll have to find another way.
I disabled that part for now so it shouldn't *need* xxd(I'm still building).

I'll edit the title for others to find
