### ISSUE TITLE
rmarkdown and pandoc

### ISSUE THREAD

**Issue by marbotte** [jgenco/jgenco-overlay#12]
Thank you very much for your rstudio ebuilds, saved me a lot of troubles!

Since pandoc and pandoc-cli are necessary for working with rmarkdown, which is a great feature of Rstudio, would it be useful to put them as a rstudio dependency, maybe activated with a "USE" such as "rmarkdown-pandoc: install dependencies for rmarkdown"?

No idea whether it is the right way to do it...

**Comment by jgenco** [comment]
I'm going to wait a bit to see if this causes any problems before I push the `quarto-cli`.

In the mean time, a few weeks ago I noticed you commented in the Rstudio middle click issue.  I made this patch for myself to make it kinda work last year.  You can place it in your [patches directory](https://wiki.gentoo.org/wiki//etc/portage/patches) and rebuild Rstudio

```diff
--- a/src/cpp/desktop/DesktopGwtCallback.cpp
+++ b/src/cpp/desktop/DesktopGwtCallback.cpp
@@ -366,7 +366,7 @@ void GwtCallback::onClipboardSelectionChanged()
 
        // when one clicks on an Ace instance, a hidden length-one selection
        // will sneak in here -- explicitly screen those out
-       if (text == QStringLiteral("\x01"))
+       if (text == QStringLiteral("\x01") || text.length() == 0)
        {
           // ignore the next clipboard change (just in case modifying it below triggers
           // this slot recursively)
@@ -488,7 +488,6 @@ void GwtCallback::setGlobalMouseSelection(QString selection)
    QClipboard* clipboard = QApplication::clipboard();
    if (clipboard->supportsSelection())
       clipboard->setText(selection, QClipboard::Selection);
-   s_globalMouseSelection = selection;
 #endif
 }
 
```
It has a couple  known problems.
* Multi line highlight in `source` mode only copies the last line or so.  *Technically* it copies the whole thing and than overwrites with the last line or so.   I *think* this is a new bug but its been awhile.
* It can't tell the difference between highlighting with the mouse and the keyboard. 
* You can't highlight zero characters; If that is even possible.
* It only works with `QT5`

**Comment by marbotte** [comment]
Thanks a lot.

Concerning pandoc, I believe that there has been a change and now pandoc itself (it is the haskell library not the cli program) does not work for rmarkdown and pandoc-cli is needed (I use the haskell overlay), but I should say I did not investigate much more...

**Comment by marbotte** [comment]
Thanks for the patch, I've never used the patch directory... I'll read the page!

**Comment by marbotte** [comment]
Your patch worked, thanks!!!
