### ISSUE TITLE
CMake Error at src/cpp/core/CMakeLists.txt:329 (find_library):   Could not find HUNSPELL_LIBRARIES using the following names: hunspell

### ISSUE THREAD

**Issue by sylvyo** [jgenco/jgenco-overlay#13]
Compiling the last version:
rstudio-2023.06.1.524
in gentoo, I get an error:

>>> Emerging (1 of 1) sci-mathematics/rstudio-2023.06.1.524::jgenco
 * rstudio-2023.06.1.524.tar.gz BLAKE2B SHA512 size ;-) ...                                                                               [ ok ]
 * Using: openjdk-bin-11
>>> Unpacking source...
>>> Unpacking rstudio-2023.06.1.524.tar.gz to /var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work
>>> Source unpacked in /var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work
>>> Preparing source in /var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524 ...
 * Applying rstudio-2022.12.0.353-qtsingleapplication.patch ...                                                                           [ ok ]
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524_build"
 * Applying rstudio-2023.03.0-386-cmake-bundled-dependencies.patch ...                                                                    [ ok ]
 * Applying rstudio-1.4.1717-fix-boost-version-check.patch ...                                                                            [ ok ]
 * Applying rstudio-2022.07.0.548-resource-path.patch ...                                                                                 [ ok ]
 * Applying rstudio-1.4.1106-server-paths.patch ...                                                                                       [ ok ]
 * Applying rstudio-2022.07.0.548-package-build.patch ...
patching file src/cpp/CMakeLists.txt
Hunk #1 succeeded at 237 with fuzz 2 (offset 13 lines).
patching file src/cpp/desktop/CMakeLists.txt
Hunk #1 succeeded at 333 (offset 12 lines).                                                                                               [ ok ]
 * Applying rstudio-2022.07.0.548-pandoc_path_fix.patch ...
patching file CMakeGlobals.txt
Hunk #1 succeeded at 232 with fuzz 2.
patching file src/cpp/session/include/session/SessionConstants.hpp
Hunk #1 succeeded at 141 with fuzz 1 (offset 3 lines).                                                                                    [ ok ]
 * Applying rstudio-2022.07.0.548-quarto-version.patch ...                                                                                [ ok ]
 * Applying rstudio-2023.06.0.421-node_electron_cmake.patch ...                                                                           [ ok ]
 * Applying rstudio-2022.07.0.548-reenable-sandbox.patch ...                                                                              [ ok ]
 * Applying rstudio-2022.07.0.548-libfmt.patch ...                                                                                        [ ok ]
 * Applying rstudio-2022.12.0.353-hunspell.patch ...                                                                                      [ ok ]
 * Applying rstudio-2022.12.0.353-add-support-for-RapidJSON.patch ...                                                                     [ ok ]
 * Applying rstudio-2022.12.0.353-system-clang.patch ...                                                                                  [ ok ]
 * Applying rstudio-2023.03.0.386-panmirror_disable.patch ...                                                                             [ ok ]
 * Adjusting to prefix /
 *   LibClang.cpp ...                                                                                                                     [ ok ]
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524_build"
cmake -C /var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DRSTUDIO_INSTALL_SUPPORTING=/usr/share/rstudio -DRSTUDIO_TARGET=TRUE -DRSTUDIO_SERVER=TRUE -DRSTUDIO_DESKTOP=TRUE -DRSTUDIO_ELECTRON=FALSE -DRSTUDIO_UNIT_TESTS_DISABLED=ON -DRSTUDIO_USE_SYSTEM_BOOST=ON -DGWT_BUILD=OFF -DGWT_COPY=ON -DRSTUDIO_USE_SYSTEM_YAML_CPP=ON -DRSTUDIO_PACKAGE_BUILD=1 -DRSTUDIO_BIN_PATH=/usr/bin -DQUARTO_ENABLED=no -DRSTUDIO_USE_SYSTEM_SOCI=TRUE -DQT_QMAKE_EXECUTABLE=/usr/lib64/qt5/bin/qmake -DRSTUDIO_INSTALL_FREEDESKTOP=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524_build/gentoo_toolchain.cmake /var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524
loading initial cache file /var/tmp/portage/sci-mathematics/rstudio-2023.06.1.524/work/rstudio-2023.06.1-524_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 13.1.1
-- The CXX compiler identification is GNU 13.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building RStudio 2023.06.1+524
-- Machine architecture: x86_64
-- CMake build type: Release
fatal: not a git repository (or any of the parent directories): .git
-- Using RStudio tools root: /opt/rstudio-tools/x86_64
-- LSB release: gentoo
-- Configured to install GWT
-- Configured to build with libpam features
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Found Boost: /usr/lib64/cmake/Boost-1.82.0/BoostConfig.cmake (found suitable version "1.82.0", minimum required is "1.78.0")  
-- Found Boost: /usr/lib64/cmake/Boost-1.82.0/BoostConfig.cmake (found suitable version "1.82.0", minimum required is "1.78.0") found components: atomic chrono date_time filesystem iostreams program_options random regex system thread 
-- No Crashpad libraries found under /opt/rstudio-tools/x86_64/crashpad/crashpad/out/Default/obj. Crashpad integration disabled.
-- SOCI libraries found under 
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "3.1.1")  
-- Performing Test HAVE_SCANDIR_POSIX
-- Performing Test HAVE_SCANDIR_POSIX - Success
-- Looking for SA_NOCLDWAIT
-- Looking for SA_NOCLDWAIT - found
-- Looking for SO_PEERCRED
-- Looking for SO_PEERCRED - found
-- Looking for inotify_init1
-- Looking for inotify_init1 - found
-- Looking for getpeereid
-- Looking for getpeereid - not found
-- Looking for setresuid
-- Looking for setresuid - found
-- Looking for group_member
-- Looking for group_member - found
-- Performing Test HAVE_EXECINFO
-- Performing Test HAVE_EXECINFO - Success
-- Performing Test PAM_MESSAGE_CONST
-- Performing Test PAM_MESSAGE_CONST - Success
-- Found PAM: /usr/lib64/libpam.so;/usr/lib64/libdl.a
CMake Error at src/cpp/core/CMakeLists.txt:329 (find_library):
  Could not find HUNSPELL_LIBRARIES using the following names: hunspell

**Comment by sylvyo** [comment]
my emerge --info:

Portage 3.0.49 (python 3.11.4-final-0, default/linux/amd64/17.1/desktop/plasma, gcc-13, glibc-2.37-r3, 6.4.3-gentoo x86_64)
=================================================================
System uname: Linux-6.4.3-gentoo-x86_64-AMD_Ryzen_9_5900HS_with_Radeon_Graphics-with-glibc2.37
KiB Mem:    32264880 total,   6116956 free
KiB Swap:   34814972 total,  33423612 free
Timestamp of repository gentoo: Tue, 18 Jul 2023 18:00:01 +0000
Head commit of repository gentoo: ee53894615282e0ecd19f46bc8c980ac7ca6e42c
Timestamp of repository booboo: Mon, 17 Jul 2023 09:47:26 +0000
Head commit of repository booboo: c131d90d8a293159bb815d5025be16992bfc9fb6

Timestamp of repository electron: Mon, 17 Jul 2023 09:47:48 +0000
Head commit of repository electron: 572e2e4586fc7ea67a9a7d5449ec08d59c013a7d

Head commit of repository jgenco: a6760cebb884201cc3aee44008fecff8f8972ddc

Timestamp of repository pentoo: Mon, 17 Jul 2023 21:31:47 +0000
Head commit of repository pentoo: 5246f9ede76b8a0d5caeb1cbcb7f87febc6f12e2

Timestamp of repository pf4public: Tue, 18 Jul 2023 16:31:46 +0000
Head commit of repository pf4public: 28a0564a81c22cac90357b3fa7b8cc56cd660f48

Timestamp of repository steam-overlay: Mon, 17 Jul 2023 09:47:32 +0000
Head commit of repository steam-overlay: 397d1cf9706d05e76ba19ecef13bc08089eb2920

sh bash 5.2_p15-r6
ld GNU ld (Gentoo 2.40 p5) 2.40.0
app-misc/pax-utils:        1.3.7::gentoo
app-shells/bash:           5.2_p15-r6::gentoo
dev-java/java-config:      2.3.1-r1::gentoo
dev-lang/perl:             5.38.0-r1::gentoo
dev-lang/python:           3.10.12::gentoo, 3.11.4::gentoo, 3.12.0_beta4::gentoo
dev-lang/rust:             1.70.0::gentoo
dev-util/cmake:            3.26.4-r1::gentoo
dev-util/meson:            1.2.0::gentoo
sys-apps/baselayout:       2.14::gentoo
sys-apps/openrc:           0.48::gentoo
sys-apps/sandbox:          2.37::gentoo
sys-devel/autoconf:        2.13-r8::gentoo, 2.71-r7::gentoo
sys-devel/automake:        1.16.5-r1::gentoo
sys-devel/binutils:        2.40-r5::gentoo
sys-devel/binutils-config: 5.5::gentoo
sys-devel/clang:           14.0.6-r4::gentoo, 15.0.7-r3::gentoo, 16.0.6::gentoo
sys-devel/gcc:             12.3.1_p20230623::gentoo, 13.1.1_p20230527::gentoo
sys-devel/gcc-config:      2.11::gentoo
sys-devel/libtool:         2.4.7-r1::gentoo
sys-devel/lld:             15.0.7::gentoo, 16.0.6::gentoo
sys-devel/llvm:            14.0.6-r4::gentoo, 15.0.7-r3::gentoo, 16.0.6::gentoo
sys-devel/make:            4.4.1-r1::gentoo
sys-kernel/linux-headers:  6.4::gentoo (virtual/os-headers)
sys-libs/glibc:            2.37-r3::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    volatile: False
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts: 
    sync-rsync-verify-max-age: 24

booboo
    location: /var/db/repos/booboo
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/booboo.git
    masters: gentoo
    volatile: False

electron
    location: /var/db/repos/electron
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/electron.git
    masters: gentoo
    volatile: False

jgenco
    location: /var/db/repos/jgenco
    sync-type: git
    sync-uri: https://github.com/jgenco/jgenco-overlay
    masters: gentoo
    volatile: False

localrepo
    location: /var/db/repos/localrepo
    masters: gentoo
    volatile: False

pentoo
    location: /var/db/repos/pentoo
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/pentoo.git
    masters: gentoo
    volatile: False

pf4public
    location: /var/db/repos/pf4public
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/pf4public.git
    masters: gentoo
    volatile: False

steam-overlay
    location: /var/db/repos/steam-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/steam-overlay.git
    masters: gentoo
    volatile: False

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -march=znver3 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-O2 -march=znver3 -pipe"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GDK_PIXBUF_MODULE_FILE GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-O2 -march=znver3 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -march=znver3 -pipe"
GENTOO_MIRRORS="https://gentoo.mirror.garr.it/ https://mirror.init7.net/gentoo/"
LANG="it_IT.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LEX="flex"
LINGUAS="it en it_IT en_US"
MAKEOPTS="--jobs 14 --load-average 15"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/bash"
USE="X a52 aac acl acpi activities alsa amd64 bluetooth branding bzip2 cairo cdda cdr cli crypt cups dbus declarative djvu dri dri3 dts dvd dvdr elogind encode exif ffmpeg fftw flac fortran gdbm gif gles2 gpm gtk gui hidpi iconv icu id3tag ipv6 javafx jpeg kde kdesu kwallet lcms libinput libnotify libtirpc mad mng mp3 mp4 mpeg mtp multilib ncurses networkmanager nls nptl ntfs objc ogg opengl openmp opus pam pango pcre pcsc-lite pdf pipewire plasma png policykit ppds pulseaudio qml qt5 readline s3tc samba screencast sdl seccomp semantic-desktop sound spell split-usr ssl startup-notification svg test-rust theora tiff touchpad truetype udev udisks unicode upower usb uxa v4l vaapi vdpau vorbis vpx vulkan wayland widgets wxwidgets x264 xattr xcb xft xml xv xvid xvmc zlib" ABI_X86="64 32" ADA_TARGET="gnat_2021" ALSA_CARDS="snd_hda_intel" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" CAMERAS="*" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="joystick wacom synaptics evdev libinput" KERNEL="linux" L10N="it en" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php8-1" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_11" PYTHON_TARGETS="python3_11" RUBY_TARGETS="ruby31" SANE_BACKENDS="*" VIDEO_CARDS="amdgpu radeonsi nvidia vesa v4l v4l2 modesetting fbdev" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LFLAGS, LIBTOOL, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

**Comment by jgenco** [comment]
I'm guessing you have `app-text/hunspell-1.7.2-r1` installed. 

hunspell-1.7.2-r1 doesn't create the symlink libhunspell.so note [lines 78-87](
https://github.com/gentoo/gentoo/blob/76592757bc94450e7add7babd487a314f9bef5e6/app-text/hunspell/hunspell-1.7.2.ebuild#L78-L81) was removed from [hunspell-1.7.2-r1](https://github.com/gentoo/gentoo/blob/76592757bc94450e7add7babd487a314f9bef5e6/app-text/hunspell/hunspell-1.7.2-r1.ebuild#L78)

 I have pushed a fix so cmake should now find the correct file.
