### ISSUE TITLE
Deno compiling problem

### ISSUE THREAD

**Issue by latot** [jgenco/jgenco-overlay#14]
Hi, I was trying to install quarto-cli and I was not able to install it because deno fails to install.

I have tested 1.31.1 and 1.33.1 both fails with the same errors.

[build.log](https://github.com/jgenco/jgenco-overlay/files/12175452/build.log)

Seems to be a bug on the code.

Thx!

**Comment by jgenco** [comment]
While double checking links to upstream sources I discovered https://github.com/dprint/dprint-plugin-json/pull/12 and I'm sure this tiny patch will fix this. 
I'm currently building `deno-1.33.1` with 
```
rustc -vV
rustc 1.70.0 (90c541806 2023-05-31) (gentoo)
binary: rustc
commit-hash: 90c541806f23a127002de5b4038be731ba1458ca
commit-date: 2023-05-31
host: x86_64-unknown-linux-gnu
release: 1.70.0
LLVM version: 16.0.6
```
to confirm but it will be hours for me.

**Comment by latot** [comment]
Hi, actually there is some relations:

quarto 1.3.433 only works with deno 1.31.1

I'm trying to use quarto 1.4.226 with deno 1.33.1, but quarto failed due to some problems with deno.

[build.log](https://github.com/jgenco/jgenco-overlay/files/12176906/build.log)

I'm able to confirm that patch fixes deno compilation, but fails quarto, that patch will works on deno 1.31.1? if that is the case would be the fix to install quarto 1.3.433.

**Comment by jgenco** [comment]
Yeah, this should work for  `deno-1.31.1`, `deno-1.30.2` and `deno-1.29.4`(If they are still needed).

**Comment by jgenco** [comment]
I added `<virtual/rust-1.70` to deno-1.31.1 and deno-1.33.1.  They both past their tests and work with quarto-cli 1.3 and 1.4 respectfully.   
I forgot `typst` was upgraded to 0.6.0 for quarto-cli 1.4 and that necessitated upgrading to rust 1.70.  I have now added `deno-1.34.3` (7c9826a9f3737d5d0c5f2917d25718e1b8d4191b) which compiles with rust-1.70 so the above hack should not be necessary.

**Comment by jgenco** [comment]
I'm closing this as I've test `deno-1.34.3` with `rust-1.71.1` so it should work for the conceivable future.

If I missed something please reopen as rereading this tread even I got confused/forgot some of this details.
