### ISSUE TITLE
Missing files in manifest

### ISSUE THREAD

**Issue by stainesa** [jgenco/jgenco-overlay#2]
Hi,
rstudio-9999-qt-5.15.patch and rstudio-9999-qt6.patch are both mentioned in the manifest, but seem not to be in the repository, or at least not with the other patch files?
As a results the ebuild crashes out.
Assistance welcomed!

**Comment by jgenco** [comment]
Sorry about that I didn't think it would care about the missing files.

**Comment by stainesa** [comment]
Fixed perfectly
Thanks!
