### ISSUE TITLE
deno-1.37.2 fails with certain GCC versions

### ISSUE THREAD

**Issue by fvalenduc** [jgenco/jgenco-overlay#21]
deno-1.37.2 fails to build with rust-1.74.1 which is the current stable release in gentoo. It ends with this error:

  ninja: job failed: g++ -MMD -MF obj/third_party/abseil-cpp/absl/status/status/status_payload_printer.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=52399655fdafdd14ade17ab12ddc9e955423aa5a -D_LIBCPP_ENABLE_ASSERTIONS=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DABSL_ALLOCATOR_NOTHROW=1 -I../../../../cargo_home/gentoo/v8-0.79.2 -Igen -I../../../../cargo_home/gentoo/v8-0.79.2/buildtools/third_party/libc++ -I../../../../cargo_home/gentoo/v8-0.79.2/third_party/abseil-cpp -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -gdwarf-4 -g1 -fno-builtin-abs -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -std=gnu++2a -fno-exceptions -fno-rtti -nostdinc++ -isystem../../../../cargo_home/gentoo/v8-0.79.2/buildtools/third_party/libc++/trunk/include -isystem../../../../cargo_home/gentoo/v8-0.79.2/buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -Wno-narrowing -Wno-class-memaccess -c ../../../../cargo_home/gentoo/v8-0.79.2/third_party/abseil-cpp/absl/status/status_payload_printer.cc -o obj/third_party/abseil-cpp/absl/status/status/status_payload_printer.o
  ninja: job failed: g++ -MMD -MF obj/third_party/abseil-cpp/absl/status/status/status.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -DCR_LIBCXX_REVISION=52399655fdafdd14ade17ab12ddc9e955423aa5a -D_LIBCPP_ENABLE_ASSERTIONS=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DABSL_ALLOCATOR_NOTHROW=1 -I../../../../cargo_home/gentoo/v8-0.79.2 -Igen -I../../../../cargo_home/gentoo/v8-0.79.2/buildtools/third_party/libc++ -I../../../../cargo_home/gentoo/v8-0.79.2/third_party/abseil-cpp -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -gdwarf-4 -g1 -fno-builtin-abs -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -Wno-psabi -std=gnu++2a -fno-exceptions -fno-rtti -nostdinc++ -isystem../../../../cargo_home/gentoo/v8-0.79.2/buildtools/third_party/libc++/trunk/include -isystem../../../../cargo_home/gentoo/v8-0.79.2/buildtools/third_party/libc++abi/trunk/include -fvisibility-inlines-hidden -Wno-narrowing -Wno-class-memaccess -c ../../../../cargo_home/gentoo/v8-0.79.2/third_party/abseil-cpp/absl/status/status.cc -o obj/third_party/abseil-cpp/absl/status/status/status.o
  ninja: subcommands failed
  thread 'main' panicked at /var/tmp/portage/net-libs/deno-1.37.2/work/cargo_home/gentoo/v8-0.79.2/build.rs:762:3:
  assertion failed: ninja(&gn_out_dir, maybe_env).arg(target).status().unwrap().success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

Furthermore, it should depends on dev-build/gn instead of dev-util/gn

**Comment by fvalenduc** [comment]
[build.log](https://github.com/jgenco/jgenco-overlay/files/14155804/build.log)

**Comment by stelinux01** [comment]
Hi, I've obtained the same error of fvalenduc with rust 1.74, 1,73 and 1,71 with the same backtrace. Could there be another cause of the error? I'm not an expert in rust backtrace

**Comment by jgenco** [comment]
Yes, I was doing some testing before I commented.  I have successfully built `deno` on Rust 1.74.1 and so far seems to work.

The error is happening in the V8 crate which is not Rust but mostly C/C++ code.   V8 normally uses clang/llvm to build but I try to accommodate people using GCC.   I'm using `GCC 12.3.1_p20240112` and seems to work.  I tried `GCC 13.2.1 20240113` and it failed. I don't use clang/llvm as I assume it will work.

This might help point to a temporary solution until a permanent solution is found.

**Comment by fvalenduc** [comment]
Indeed, it works with clang and llvm. Thanks for your information.

**Comment by fvalenduc** [comment]
The limitation on rust version could thus be adapted to include also rust-1.74.1 which is also needed nowadays to build the stable version of chromium.

**Comment by jgenco** [comment]
Ah, didn't know that.  The reason I limit Rust versions is because in the past there was a weird runtime error with certain Rust versions. see https://github.com/jgenco/jgenco-overlay/issues/14#issuecomment-1652504206

What GCC version failed for you? 

And future readers: The ebuild also tries to work with your chosen linker (except mold) as well.  Upstream prefers the combination clang/llvm with lld.

**Comment by fvalenduc** [comment]
Finally, clang didn't work. The current stable version of gcc (13.2.1_p20240113-r1) also fails. As you said, gcc-12 (12.3.1_p20240112) works.

**Comment by jgenco** [comment]
Update: I added back `use_custom_libcxx=false` for GCC section. I removed it thinking `export DISABLE_CLANG=true` would handle every thing.  I was wrong all it did was set `is_clang=false` which is what it replaced. :(
Hopefully that fixes GCC 12 and 13. They both passed all of Deno's tests on my system.

I have never tried building with Clang/llvm as I just assumed it would work.  What version did you use when it failed? And how did it fail?

**Comment by fvalenduc** [comment]
Indeed, it compile fine with GCC 13 with the lastest changes. With clang 17, I get this error:

  libtool: compile:  clang -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -Wall -O0 -ffunction-sections -fdata-sections -fPIC --target=x86_64-unknown-linux-gnu -O2 -pipe -march=skylake --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=8192 -O2 -pipe -march=skylake --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=8192 -fexceptions -MT src/tramp.lo -MD -MP -MF src/.deps/tramp.Tpo -c ../src/tramp.c  -fPIC -DPIC -o src/tramp.o
  make[2]: Leaving directory '/var/tmp/portage/net-libs/deno-1.37.2/work/deno-1.37.2/target/release/build/libffi-sys-e018e7d82a3fe7e1/out/libffi-build/x86_64-unknown-linux-gnu'
  make[1]: Leaving directory '/var/tmp/portage/net-libs/deno-1.37.2/work/deno-1.37.2/target/release/build/libffi-sys-e018e7d82a3fe7e1/out/libffi-build/x86_64-unknown-linux-gnu'

  --- stderr
  clang: error: unsupported option '-print-multi-os-directory'
  clang: error: no input files

**Comment by fvalenduc** [comment]
[build-clang.log](https://github.com/jgenco/jgenco-overlay/files/14178704/build-clang.log)

**Comment by jgenco** [comment]
This should hopefully fix it.  I added a copy of a patch from dev-libs/libffi::gentoo to the rust crate.

Normally it ads `no-implicit-function-declaration` to the compile flag to stop >=clang-16 from failing.  For some reason the cache flags stop it from adding this.

**Comment by fvalenduc** [comment]
Indeed, it works also with clang now. So this bug is completely solved I think.

**Comment by jgenco** [comment]
I believe so too.  Sorry for the trouble and thanks for helping me find the other bugs and confirming their fixes.
