### ISSUE TITLE
manifest failure for app-text/quarto-cli

### ISSUE THREAD

**Issue by fvalenduc** [jgenco/jgenco-overlay#28]
When compiling quarto-cli-1.5.53, a manifest failure occurs:

Resolving codeload.github.com... 140.82.121.9
Connecting to codeload.github.com|140.82.121.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘/var/cache/distfiles/deno_std@0.217.0.tar.gz.__download__’

/var/cache/distfile     [ <=>                ] 922.18K  4.86MB/s    in 0.2s    

2024-07-19 19:23:51 (4.86 MB/s) - ‘/var/cache/distfiles/deno_std@0.217.0.tar.gz.__download__’ saved [944317]

!!! Fetched file: deno_std@0.217.0.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      944317
!!! Expected: 944447
Refetching... File renamed to '/var/cache/distfiles/deno_std@0.217.0.tar.gz._checksum_failure_.2_fgz57r'

**Comment by fvalenduc** [comment]
The same failure occurs for quarto-cli-1.6.0:

/var/cache/distfile     [ <=>                ] 922.18K  4.71MB/s    in 0.2s    

2024-07-19 19:30:48 (4.71 MB/s) - ‘/var/cache/distfiles/deno_std@0.217.0.tar.gz.__download__’ saved [944317]

!!! Fetched file: deno_std@0.217.0.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      944317
!!! Expected: 944447
Refetching... File renamed to '/var/cache/distfiles/deno_std@0.217.0.tar.gz._checksum_failure_.2_fgz57r'

!!! Couldn't download 'deno_std@0.217.0.tar.gz'. Aborting.

**Comment by jgenco** [comment]
They renamed the folder in the tarball from `deno_std-0.217.0` -> `std-0.217.0` no files where changed.

I assume `quarto-cli-1.4.555` is also affected but I was planning to stabilize `quarto-cli-1.5.x` this weekend so I'm not worried about it.
