### ISSUE TITLE
net-libs/deno fails to compile

### ISSUE THREAD

**Issue by stainesa** [jgenco/jgenco-overlay#3]
net-libs deno compilation stops here - looks like an issue downloading some stuff from Google? Any suggested bypass? Do I need authorisation to download these?
Thanks,
Anthony
rustc-link-lib=static=rusty_v8
  building v8 lockfile: "/var/tmp/portage/net-libs/deno-1.22.0/work/deno-1.22.0/target/release/build/building_v8.fslock"
  using Chromiums clang
  clang_base_path /var/tmp/portage/net-libs/deno-1.22.0/work/deno-1.22.0/target/release/clang
  Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz 
  <urlopen error [Errno -3] Temporary failure in name resolution>
  Retrying in 5 s ...
  Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz 
  <urlopen error [Errno -3] Temporary failure in name resolution>
  Retrying in 10 s ...
  Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz 
  <urlopen error [Errno -3] Temporary failure in name resolution>
  Retrying in 20 s ...
  Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-llvmorg-12-init-11060-g118c3f3c-1.tgz 
  <urlopen error [Errno -3] Temporary failure in name resolution>
  Failed to download prebuilt clang package clang-llvmorg-12-init-11060-g118c3f3c-1.tgz
  Use build.py if you want to build locally.
  Exiting.

**Comment by jgenco** [comment]
Before looking to deeply right now. I think it either can't find clang/llvm or it wants clang version 12.  The code seems to point to the former.  When it can't find clang it tries to download clang so it can compile V8.
For reference I have clang 12,13,14. Hopefully clang 13 works as I see version 12 is not in the tree.

**Comment by stainesa** [comment]
Hi,
Thanks for getting back to me.

I don't have clang installed, but will do it now (takes a while), and come back to you shortly. This will be sys-devel/clang-runtime-14.0.6 and friends.

The build gets much further (10,000 lines not 2,200) but ends like this
 ```
ninja: Entering directory `/var/tmp/portage/net-libs/deno-1.22.0/work/deno-1.22.0/target/release/gn_out'
  [1/1154] STAMP obj/v8/torque_base.stamp
  [2/1154] LINK ./gen-regexp-special-case
  FAILED: gen-regexp-special-case
  python "../../../../cargo_home/gentoo/v8-0.42.1/build/toolchain/gcc_link_wrapper.py" --output="./gen-regexp-special-case">
  clang-14: error: invalid linker name in argument '-fuse-ld=lld'
  [3/1154] LINK ./bytecode_builtins_list_generator
  FAILED: bytecode_builtins_list_generator
  python "../../../../cargo_home/gentoo/v8-0.42.1/build/toolchain/gcc_link_wrapper.py" --output="./bytecode_builtins_list_g>
  clang-14: error: invalid linker name in argument '-fuse-ld=lld'
  [4/1154] LINK ./torque
  FAILED: torque
  python "../../../../cargo_home/gentoo/v8-0.42.1/build/toolchain/gcc_link_wrapper.py" --output="./torque" -- ../../../../.>
  clang-14: error: invalid linker name in argument '-fuse-ld=lld'
  ninja: build stopped: subcommand failed.
  --- stderr
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1
```

I then installed **sys-devel/lld-14.0.6::gentoo** and it worked!
(or at least got to the end of net-libs/deno-1.22...)
Thank you,
Anthony

**Comment by stainesa** [comment]
And it all installs, and seems to run well.
One warnign message only 
 Messages for package net-libs/deno-1.22.0:

 * cargo ebuild noted one vulnerabilities
 * Crate: time@0.1.44   - Potential segfaults
 * Url:   https://rustsec.org/advisories/RUSTSEC-2020-0071

This does not seem very serious at all.
Thank you again,
Anthony

**Comment by jgenco** [comment]
Good to here. Thanks for the report because I think sys-devel/lld might be able to be turned off.

That warning is from the command "cargo ebuild" and I passed it along.  I agree it doesn't sound like a security problem and its not in the deno-1.25.x builds.

**Comment by stainesa** [comment]
Thank you!
