### ISSUE TITLE
dev-java/gwt fails, eclass change

### ISSUE THREAD

**Issue by hendrack** [jgenco/jgenco-overlay#30]
Hi. I built gwt, rstudio etc. a week ago successfully. Now fails on another machine. I think you need to change your ebuilds to some eclass changes.

var/tmp/portage/dev-java/gwt-2.9.0-r4/temp/environment: line 2993: **java-pkg-2_src_compile: command not found

See: https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/java-pkg-2.eclass?id=cb2cde8fccc89412e914986153bf706e3c16a63a (java-pkg-2.eclass: remove unused eclass functions java-pkg-2_src_{compile,test})

**Comment by jgenco** [comment]
Thanks, I copied the previous version of [java-pkg-2.eclass](https://github.com/gentoo/gentoo/blob/7064b9d129ab92043296c3a8e60a1c63789d3476/eclass/java-pkg-2.eclass).
I should probably come up a better option but this will do for now.
