### ISSUE TITLE
net-libs/deno and app-text/typst depends on virtual/rust which will soon be removed

### ISSUE THREAD

**Issue by fvalenduc** [jgenco/jgenco-overlay#33]
Almost everything is in the subject. The way dependencies on rust are specified in ebuild has drastically changed today. virtual/rust is not used anymore and will be removed in 30 days. So the ebuilds for deno and typst needs to be adapted to this change.

**Comment by jgenco** [comment]
Yeah, I woke up today to that greeting.  I knew they where working on it but I didn't know it would be this soon or they where getting rid of `virtual/rust`.

It looks like a simple change which I have made on a local branch. Hopefully by tonight, probably tomorrow, I'll push it.

**Comment by jgenco** [comment]
That should fix it. I'll leave this open to collect any problems.
On a positive note, discovered `app-text/typst-0.11.0` had testing problems with `rust-1.82.0`.

**Comment by fvalenduc** [comment]
I think you can close the bug. I installed the new versions of typst and deno with rust-1.81. Afterwards I could remove virtual/rust with emerge --depclean
