### ISSUE TITLE
deno fails to compile

### ISSUE THREAD

**Issue by ilikegitlab** [jgenco/jgenco-overlay#35]
First I got:
  thread 'main' panicked at /var/tmp/portage/net-libs/deno-1.46.3-r1/work/cargo_home/gentoo/bindgen-0.69.4/lib.rs:622:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"

Then I updated llvm to 19.1.6. I 
[build.log.gz](https://github.com/user-attachments/files/18254826/build.log.gz)
now seem to get past that step but the build fails with some errors I do not really understand how to fix. Probably another version issue. Build log is attached.

**Comment by ilikegitlab** [comment]
downgraded to 18.1.8 and now it works. sorry for the noise.

**Comment by jgenco** [comment]
No problem, you found two bugs in the deno ebuild.

1. bindgen@0.68.4 only works with clang <19.  Using a tiny upstream patch allows bindgen to work with clang 19.1.
2. Even with `-llvm`, deno dependency `bindgen` requires clang to build the file src_binding.rs.
Perhaps a future version of bindgen won't need clang or maybe if src_binding.rs is generic enough I can just add the file.

I removed LLVM 20  support out of caution.
