### ISSUE TITLE
rstudio-2022.12.0.353 build failed

### ISSUE THREAD

**Issue by lschneiderbauer** [jgenco/jgenco-overlay#4]
Hi,

I tried to install rstudio from your overlay today, and ran into a build error:
```
/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/work/rstudio-2022.12.0-353/src/cpp/core/include/core/Thread.hpp:362:9: error: ‘set’ in namespace ‘std’ does not name a template type
  362 |    std::set<T, std::less<T>, std::allocator<T> > set_;
```

I am attaching the build log: [rstudio-2022.12.0.353-build.log](https://github.com/jgenco/jgenco-overlay/files/10322138/rstudio-2022.12.0.353-build.log),
[emerge-info.txt](https://github.com/jgenco/jgenco-overlay/files/10322157/emerge-info.txt)

**Comment by jgenco** [comment]
It looks like RStudio needs a small patch for boost 1.81.0.
Try this patch and place it in /etc/portage/patches/sci-mathematics/rstudio/boost.patch

```
--- a/src/cpp/core/include/core/Thread.hpp
+++ b/src/cpp/core/include/core/Thread.hpp
@@ -17,7 +17,7 @@
 #define CORE_THREAD_HPP
 
 #include <queue>
-
+#include <set>
 #include <boost/utility.hpp>
 #include <boost/function.hpp>
 

```

**Comment by lschneiderbauer** [comment]
Thank you! That patch fixed the intial error.
Now a quarto-related error pops up:
>  ERROR: NotFound: No such file or directory (os error 2), remove '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/homedir/.cache/quarto/sass/0ed187670ca06edf0fef49e29c6d8cb4.css'

[build.log](https://github.com/jgenco/jgenco-overlay/files/10326363/build.log)

**Comment by jgenco** [comment]
I'll look into that. Its failing to build the user guide.  I don't normally test with +doc.
If you want to use rstudio now you can try again with -doc.

**Comment by lschneiderbauer** [comment]
I just tested your updated dart-sass package. `sass` and `quarto check` report the "good" output from your post now.
I did not test the rstudio build with +doc yet. (-doc is working fine so far)

**Comment by jgenco** [comment]
Good to hear.  Closing as both the boost problem and doc(sass) problem seems fixed.
