### ISSUE TITLE
mathjax

### ISSUE THREAD

**Issue by Silverfox28** [jgenco/jgenco-overlay#5]
` ERROR: sci-mathematics/rstudio-2022.12.0.353::jgenco-overlay failed (prepare phase):
  /usr/share/mathjax not a directory of file
 
 Call stack:
      ebuild.sh, line  136:  Called src_prepare
    environment, line 5017:  Called bundle_ln '/usr/share/mathjax' '/dependencies/mathjax-27' 'mathjax'
    environment, line 1240:  Called die
  The specific snippet of code:
        [[ ! -d "${EPREFIX}${1}" && ! -f "${EPREFIX}${1}" ]] && die "${EPREFIX}${1} not a directory of file";
  
  If you need support, post the output of `emerge --info '=sci-mathematics/rstudio-2022.12.0.353::jgenco-overlay'`,
  the complete build log and the output of `emerge -pqv '=sci-mathematics/rstudio-2022.12.0.353::jgenco-overlay'`.
  The complete build log is located at '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/temp/build.log'.
  The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/temp/environment'.
  Working directory: '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/work/rstudio-2022.12.0-353'
 S: '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/work/rstudio-2022.12.0-353'
`

I have installed `mathjax`, but now:
`
ERROR: sci-mathematics/rstudio-2022.12.0.353::jgenco-overlay failed (compile phase):
eant failed
 Call stack:
     ebuild.sh, line  136:  Called src_compile
   environment, line 4930:  Called java-pkg-2_src_compile
   environment, line 2863:  Called eant 'build' '-f' 'src/gwt/build.xml' '-Dbuild.dir=bin' '-Dwww.dir=www' '-Dextras.dir=extras' '-Dlib.dir=lib' '-Dgwt.main.module=org.rstudio.studio.RStudioDesktop' '-DlocalWorkers=15'
   environment, line 1775:  Called die
 The specific snippet of code:
       ant ${antflags} "${@}" || die "eant failed"
 
  If you need support, post the output of `emerge --info '=sci-mathematics/rstudio-2022.12.0.353::jgenco-overlay'`,
  the complete build log and the output of `emerge -pqv '=sci-mathematics/rstudio-2022.12.0.353::jgenco-overlay'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=openjdk-bin-8  CLASSPATH="" JAVA_HOME="/opt/openjdk-bin-8.332_p09"
JAVACFLAGS="-source 11 -target 11" COMPILER="javac"
and of course, the output of emerge --info =rstudio-2022.12.0.353
  The complete build log is located at '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/temp/build.log'.
  The ebuild environment file is located at '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/temp/environment'.
  Working directory: '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/work/rstudio-2022.12.0-353'
  S: '/var/tmp/portage/sci-mathematics/rstudio-2022.12.0.353/work/rstudio-2022.12.0-353'

>>> Failed to emerge sci-mathematics/rstudio-2022.12.0.353, Log file:
`

**Comment by jgenco** [comment]
build.log:
`* Using: openjdk-bin-8`

It looks like Rstudio does not like Java version 8.  I  tried using openjdk-bin-8 and it failed the same way.  
If you have not, emerge  virtual/jdk:11 . You might need to use `eselect java-vm` to change you java-vm to 11. You can change it back once your done.
The last jdk-8 that compiled was 2021.09.2_p382 with icedtea-bin-8.
